Djangoproj/urls.py
from django.contrib import admin
from django.urls import path, include
from minesite.views import main_minesite

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('minesite/', include(('minesite.urls', 'minesite'), namespace='minesite')),
    path('', main_minesite, name="main_minesite"),
]

minesite/urls.py
from minesite.views import *
from django.views.generic import TemplateView
from django.urls import path, include

urlpatterns = [
    #path('',TemplateView.as_view(template_name = "login.html"), name = "login"),
    path('', login, name = 'login'),
    #path('signup/', TemplateView.as_view(template_name = "signup.html"), name = 'signup'),
    path('signup/', signup, name = 'signup'),
    path('flightbooking/<str:username>/',select_flight,name="select_flight"),
    path('mytransactions/<str:username>/',mytransactions,name="mytransactions"),
    path('accountdetails/<str:username>/',account_details,name="edit_account_details"),
    path('editaccountdetails/<str:username>/',edit_account_details,name="edit_account_details"),
    path('myupcomingflights/<str:username>/',myupcomingflights,name="myupcomingflights"),
    path('transactionpage/',transaction_page, name="transaction_page"),
    path('economyseatselectionpage/', e_seatselection_page, name="e_seatselection_page"),
    path('businessseatselectionpage/', b_seatselection_page, name="b_seatselection_page"),
    path('deletetransaction/<str:transactionid>/', deletetransaction, name="deletetransaction"),
    path('deleteaccount/<str:username>/', deleteaccount, name="deleteaccount"),
    path('aboutus/', aboutus, name="aboutus"),
]   

minesite/models.py
from functools import total_ordering
from django.db.models import *

# Create your models here.
class LoginModel(Model):
    username = CharField(max_length=32)
    password = CharField(max_length=32)
    name = CharField(max_length=32)
    email = EmailField(max_length=32, null = True)

    class Meta:
        db_table = "User_Details"
        
class FlightDetails(Model):
    date = DateField()
    code = CharField(max_length=6)
    time = TimeField()
    fromplace = CharField(max_length=32)
    toplace = CharField(max_length=32)
    e_numseats = IntegerField()
    b_numseats = IntegerField()
    e_price = IntegerField()
    b_price = IntegerField()
    status = CharField(max_length=12, default="CONFIRMED")

    class Meta:
        db_table = "Flight_Details"

class Transactions(Model):
    transaction_num = IntegerField(default=0)
    username = CharField(max_length=32)
    code = CharField(max_length=6)
    time = TimeField(null=True)
    fromplace = CharField(max_length=32)
    toplace = CharField(max_length=32)
    num_passangers = IntegerField()
    total = IntegerField()
    paymentmode = CharField(max_length=16)
    flightclass = CharField(max_length=8)
    seatnumbers = CharField(max_length=4 , default="")
    mealpreferance = CharField(max_length=16, default="Vegetarian")
    flightdate = DateField(default="2021-06-17")
    flighttime = TimeField(default="12:00:00")

    def __str__(self):
        return self.seatnumbers

    class Meta:
        db_table = "Transactions"

minesite/forms.py
from django.forms import *
from minesite.models import LoginModel
from django.shortcuts import render

class LoginForm(Form):
    username = CharField(max_length=32)
    password = CharField(max_length=32, widget=PasswordInput)

    '''def cleaned_info(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        return {"username":username,"password":password} '''

class SignupForm(Form):
    name = CharField(max_length=32)
    username = CharField(max_length = 32)
    password = CharField(max_length = 32, widget=PasswordInput)
    confirmpassword = CharField(max_length = 32, widget = PasswordInput)
    email = EmailField()

minesite/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from minesite.models import *
from minesite.forms import *
from minesite.classes import *
from datetime import date, datetime

def main_minesite(request):
    return render(request, "main_minesite.html")

def login(request):
    username = "not logged in"
    errors = []
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        verify_data = verify(username,password)
        verify_data.r_username()
        verify_data.r_password()
        errors = verify_data.r_errors()
        try:
            dbuser = LoginModel.objects.get(username = username)
            if password != dbuser.password:
                return render(request,template_name="login.html", context={'errors':['Incorrect Password!']})
        except:
            return render(request,template_name="login.html", context={'errors':["Username does not Exist!"]})

        loginform = LoginForm(request.POST)        
        if loginform.is_valid():
            #information = loginform.cleaned_info()
            #username = information['username']
            if errors == []:
                name = dbuser.name
                username = dbuser.username
                return render(request, "homepage.html",{"name":name, 'username':username})
    else:
        loginform = LoginForm() 
    return render(request, "login.html", {'errors':errors})

def signup(request):
    errors = list()
    if request.method == "POST":
        name = request.POST['name']
        username = request.POST['username']
        password = request.POST['password']
        confirmpassword = request.POST['confirmpassword']
        email = request.POST['email']
        verify_data = verify(username,password,name,confirmpassword,email)
        verify_data.r_username()
        verify_data.r_password()
        verify_data.r_name()
        verify_data.r_confirmpassword()
        verify_data.r_email()
        errors = verify_data.r_errors()
        try:
            LoginModel.objects.get(username = username)
            errors += ["Username already exists. Please try a different Username."]
        except:
            pass
        if errors == []:
            data = LoginModel(username=username, password = password, name = name, email = email)
            data.save() 
            return render(request, "homepage.html",{"name":name})
    else:
        signupform = SignupForm()
    return render(request, "signup.html",{'errors':errors}) 

def homepage(request):
    return render(request, "homepage.html",{})

def myupcomingflights(request,username):
    transactions = Transactions.objects.filter(username=username)
    num_transactions = len(transactions)
    minetransactions = []
    for i in range(num_transactions):
        transaction = transactions[i]
        if transaction.flightdate<date.today():
            continue
        flightcode = transaction.code
        transaction_num = transaction.transaction_num
        fromplace = transaction.fromplace
        toplace = transaction.toplace
        paymentmode = transaction.paymentmode
        flightclass = transaction.flightclass
        seatnumbers = transaction.seatnumbers
        mealpreferance = transaction.mealpreferance
        flightdate = transaction.flightdate
        flighttime = transaction.flighttime
        flightdetails = FlightDetails.objects.filter(code=flightcode)[:1].get()
        status = flightdetails.status
        minetransactions += [{'code':flightcode,'transaction_num':transaction_num,'fromplace':fromplace,'toplace':toplace,'paymentmode':paymentmode,'flightclass':flightclass,'seatnumbers':seatnumbers,'mealpreferance':mealpreferance,'flightdate':str(flightdate),'flighttime':str(flighttime),'status':status}]
    return render(request,"upcomingflights.html",{'username':username,'transactions':minetransactions[-1::-1]})

def mytransactions(request,username):
    transactions = Transactions.objects.filter(username=username)
    num_transactions = len(transactions)
    minetransactions = []
    for i in range(num_transactions):
        transaction = transactions[i]
        flightcode = transaction.code
        transaction_num = transaction.transaction_num
        fromplace = transaction.fromplace
        toplace = transaction.toplace
        paymentmode = transaction.paymentmode
        flightclass = transaction.flightclass
        seatnumbers = transaction.seatnumbers
        mealpreferance = transaction.mealpreferance
        flightdate = transaction.flightdate
        flighttime = transaction.flighttime
        flightdetails = FlightDetails.objects.filter(code=flightcode)[:1].get()
        status = flightdetails.status
        minetransactions += [{'code':flightcode,'transaction_num':transaction_num,'fromplace':fromplace,'toplace':toplace,'paymentmode':paymentmode,'flightclass':flightclass,'seatnumbers':seatnumbers,'mealpreferance':mealpreferance,'flightdate':str(flightdate),'flighttime':str(flighttime),'status':status}]
    return render(request,"mytransactions.html",{'username':username,'transactions':minetransactions[-1::-1]})

def select_flight(request,username):
    errors = []
    currentdate = date.today()
    if request.method == "POST":
        fromplace = request.POST['from'].title()
        toplace = request.POST['to'].title()
        num_passangers = int(request.POST['num_passangers'])
        flightclass = request.POST['class']
        flightdate = request.POST['date']
        verify_data = verify(fromplace=fromplace,toplace=toplace)
        verify_data.r_fromplace()
        verify_data.r_toplace()
        errors = verify_data.r_errors()
        try:
            flightdetails = FlightDetails.objects.get(date=flightdate,fromplace=fromplace,toplace=toplace,status="CONFIRMED")
            if flightclass == "Economy" and flightdetails.e_numseats >0 and flightdetails.e_numseats>=num_passangers:
                price = flightdetails.e_price
                total = price*num_passangers
                flightcode = flightdetails.code
                return render(request, "transactionpage.html", {'fromplace':fromplace,'toplace':toplace,'flightclass':flightclass,'price':price,'number':num_passangers,'total':total,'flightcode':flightcode, 'username':username, 'errors':errors})
            elif flightclass == "Business" and flightdetails.b_numseats>0 and flightdetails.b_numseats>=num_passangers:
                price = flightdetails.b_price
                total = price*num_passangers
                flightcode = flightdetails.code
                return render(request, "transactionpage.html", {'fromplace':fromplace,'toplace':toplace,'flightclass':flightclass,'price':price,'number':num_passangers,'total':total,'flightcode':flightcode, 'username':username, 'errors':errors})
            else:   
                errors += [str(num_passangers)+" Seats are not Available in "+flightclass+' Class']
                return render(request, "flight_selection.html", {'username':username,'currentdate':str(currentdate), 'errors':errors})
        except:
            if errors == []: 
                try:
                    flightdetails = FlightDetails.objects.get(fromplace=fromplace)
                except:
                    errors += ['No flights from this country. Please choose another Departure Country.']
                try:
                    flightdetails = FlightDetails.objects.get(toplace=toplace)
                except:
                    errors += ['No flights to this country. Please choose another Arrival Country.']
            try:
                flightdetails = FlightDetails.objects.get(flightdate=flightdate)
            except:
                errors += ['No flights available. Please choose another Date.']
            return render(request, "flight_selection.html", {'username':username, 'currentdate':str(currentdate), 'errors':errors})
        
    return render(request, "flight_selection.html", {'username':username,'currentdate':str(currentdate), 'errors':errors})

def account_details(request,username):
    dbuser = LoginModel.objects.get(username=username)
    name = dbuser.name
    email = dbuser.email
    return render(request, "account_details.html", {"username":username, "name":name, "email":email})

def edit_account_details(request,username):
    errors = []
    if request.method == "POST":
        name = request.POST['name']
        password = request.POST['password']
        confirmpassword = request.POST['confirmpassword']
        email = request.POST['email']
        verify_data = verify(username,password,name,confirmpassword,email)
        verify_data.r_username()
        verify_data.r_password()
        verify_data.r_name()
        verify_data.r_confirmpassword()
        verify_data.r_email()
        errors = verify_data.r_errors()
        if errors == []:
            data = LoginModel.objects.get(username=username)
            data.name = name
            data.password = password
            data.email = email
            data.save()
            return render(request, "account_details_updated.html", {'username':username})
            
    dbuser = LoginModel.objects.get(username=username)
    name = dbuser.name
    email = dbuser.email
    return render(request, "edit_account_details.html", {'username':username, 'name':name, 'email':email, 'errors':errors})

def transaction_page(request):
    if request.method == "POST":
        flightcode = request.POST['flightcode']
        flightclass = request.POST['flightclass']
        num_passangers = request.POST['num_passangers']
        username = request.POST['username']
        paymentmode = request.POST['paymentmode']
        total = request.POST['total']
        flightdetails = FlightDetails.objects.get(code=flightcode)
        fromplace = request.POST.get('fromplace')
        toplace = request.POST.get('toplace')
        flightdate = flightdetails.date
        flighttime = flightdetails.time

minesite/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <title>About Us</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <body style="background-color: #162447;">
        <div class="container-fluid">
            <nav class="navbar navbar-inverse">
                <div class = "navbar-header">
                    <a class ="navbar-brand" href="#">Mine Airlines</a>
                </div>
            </nav>
                <h1 style="color:#E43F5A">About Us</h1>
                <p style="color:#cccf1e">Website created and maintained by: Metic</p>
                <p style="color:#cccf1e">My Number: buy me wine or something first</p>
                <blockquote class="blockquote">
                    <footer class="blockquote-footer">Metic</footer>
                </blockquote>
                <p><input type = "button" value = "Return to main Page" class = "btn btn-danger" onclick="window.location.href='http://127.0.0.1:8000/'"></p> 
        </div>
    </body>
</html>

minesite/templates/account_details.html
<!DOCTYPE html>
<html>
    <head>
        <title>Account Details</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
    <body style="background-color: #162447;">
        <div class="container">
        <p></p>
        <h1 style="color:#E43F5A;"> Account Details</h1>
        <p></p>
        </div>
        <div class = "container" style="padding: 2px; align-content: center; background-color: #E43F5A;">
        <h2 style="color:#1F4068">Name: {{name}}</h2>
        <p></p>
        <h2 style="color:#1F4068">Username: {{username}}</h2>
        <p></p>
        <h2 style="color:#1F4068">Email: {{email}}</h2>
        <p></p>
    </div>
    <div class="container">
        <p></p>
       <p><input type = "button" class="btn btn-success" value = "Edit Account Details" onclick="window.location.href='http://127.0.0.1:8000/minesite/editaccountdetails/{{username}}/'">
       <input type = "button" class="btn btn-warning" value = "Delete Account" onclick="window.location.href='http://127.0.0.1:8000/minesite/deleteaccount/{{username}}/'"> </p>
       <p><input type = "button" class="btn btn-danger" value = "Go Back" onclick="window.location.href='http://127.0.0.1:8000/minesite/'">
       <input type = "button" class="btn btn-danger" value = "Signout" onclick="window.location.href='http://127.0.0.1:8000/'"></p>
    </div>
    </body>
</html>

minesite/templates/account_details_updated.html
<!DOCTYPE html>
<html>
    <head>
        <title>Profile Updated</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <body style="background-color: #162447;">
        <div class = "container">
        <p></p>
        <h1 style="color:#E43F5A;">Updated your Profile!</h1>
        <input type = "button" value = "Go Back" class = "btn btn-info" onclick="window.location.href='http://127.0.0.1:8000/minesite/accountdetails/{{username}}/'">
        </div>
    </body>
</html>

minesite/templates/accountdeletedpage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Account Deleted</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <body style="background-color: #162447;">
        <div class = "container">
        <p></p>
        <h1 style="color:#E43F5A;">Account Deleted Successfully!</h1>
        <input type = "button" value = "Home Page" class = "btn btn-info" onclick="window.location.href='http://127.0.0.1:8000/'">
        </div>
    </body>
</html>

minesite/templates/b_seatselectionpage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Seat Selection</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <div class="container">
        {% if errors %}
            {% for error in errors %}
            <div class="alert alert-danger">
                <strong>Alert! </strong>{{error}}
            </div>
            {% endfor %}
        {% endif %}
        </div>
      <body style="background-color: #162447;">
        <p></p>
        <div class="container">
            <p></p>
            <h1 style="color:#E43F5A;">Select Seat</h1>
            </div>
            <p></p>
            <div class="progress">
                <div class="progress-bar bg-success" style="width:75%">
                </div>
            </div>
        <p></p>
        <form name = "seatselectionform" action = "{% url 'minesite:b_seatselection_page' %}" method = "post"> {% csrf_token %}
            <div class="container">
            <p></p>
            <h3 style="color:#E43F5A;">Booking Under: <input type="text" style="background-color:lightgoldenrodyellow" name = "username" value = {{username}} readonly/></h3>
            <h3 style="color:#E43F5A;">Flight: <input type="text" style="background-color:lightgoldenrodyellow" name = "flightcode" value = {{flightcode}} readonly/></h3>
            <h3 style="color:#E43F5A;"><label for = "food">Choose Your Meal Preferance:</label>
            <select style="background-color:lightgoldenrodyellow" name = "meal" id="meal">
                <option value = "Vegetarian">Vegetarian</option>
                <option value = "Non-Vegetarian">Non-Vegetarian</option>
                <option value = "Vegan">Vegan</option>
            </select>
            </h3>
            <h3 style="color:#E43F5A;">Select <input  type="text" style="background-color:lightgoldenrodyellow" name = "num_seats" value = {{num_seats}} readonly/> Seat(s):</h3>
            <div class="container">
            <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <td>Seat</td>
                    <td>BA</td>
                    <td>BB</td>
                    <td></td>
                    <td>BC</td>
                    <td>BD</td>
                    <td></td>
                    <td>BE</td>
                    <td>BF</td>
                </tr>
            </thead>
                {% for i in num %}
                    <tr>
                        <td>{{i}}</td>
                        <td><input type="checkbox" id = BA{{i}} value = BA{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = BB{{i}} value = BB{{i}} name = "seat"/></td>
                        <td></td>
                        <td><input type="checkbox" id = BC{{i}} value = BC{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = BD{{i}} value = BD{{i}} name = "seat"/></td>
                        <td></td>
                        <td><input type="checkbox" id = BE{{i}} value = BE{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = BF{{i}} value = BF{{i}} name = "seat"/></td>
                    </tr>
                {% endfor %}
            </table> 
            </div>
            {% for seat in bookedseats %}
            <script>
                document.getElementById("{{seat}}").disabled = true;
            </script>
            {% endfor %}
            <p><input type = "submit" class="btn btn-success" value = "Submit"/></p>
            <h4 style="color:#E43F5A;">If no Seat/Food is submitted, any available Seat(s) will be choosen. </h4>
            <h4 style="color:#E43F5A;">You're booking will not be cancelled and you will still be charged.</h4>
            <h4 style="color:#E43F5A;">Please manually Cancel your Booking from Home Page or contact Staff.</h4>
        </div>
        </form>
    </body>
</html>

minesite/templates/e_seatselectionpage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Seat Selection</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <div class="container">
        {% if errors %}
            {% for error in errors %}
            <div class="alert alert-danger">
                <strong>Alert! </strong>{{error}}
            </div>
            {% endfor %}
        {% endif %}
        </div>
      <body style="background-color: #162447;">
        <p></p>
        <div class="container">
            <p></p>
            <h1 style="color:#E43F5A;">Select Seat</h1>
            </div>
            <p></p>
            <div class="progress">
                <div class="progress-bar bg-success" style="width:75%">
                </div>
            </div>
        <p></p>
        <form name = "seatselectionform" action = "{% url 'minesite:e_seatselection_page' %}" method = "post"> {% csrf_token %}
            <div class="container">
            <p></p>
            <h3 style="color:#E43F5A;">Booking Under: <input type="text" style="background-color:lightgoldenrodyellow" name = "username" value = {{username}} readonly/></h3>
            <h3 style="color:#E43F5A;">Flight: <input type="text" style="background-color:lightgoldenrodyellow" name = "flightcode" value = {{flightcode}} readonly/></h3>
            <h3 style="color:#E43F5A;"><label for = "food">Choose Your Meal Preferance:</label>
            <select style="background-color:lightgoldenrodyellow" name = "meal" id="meal">
                <option value = "Vegetarian">Vegetarian</option>
                <option value = "Non-Vegetarian">Non-Vegetarian</option>
                <option value = "Vegan">Vegan</option>
            </select>
            </h3>
            <h3 style="color:#E43F5A;">Select <input  type="text" style="background-color:lightgoldenrodyellow" name = "num_seats" value = {{num_seats}} readonly/> Seat(s):</h3>
            <div class="container">
            <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th>Seat</th>
                    <th>A</th>
                    <th>B</th>
                    <th>C</th>
                    <th></th>
                    <th>D</th>
                    <th>E</th>
                    <th>F</th>
                    <th></th>
                    <th>G</th>
                    <th>H</th>
                    <th>I</th>
                </tr>
            </thead>
                {% for i in num %}
                    <tr>
                        <td>{{i}}</td>
                        <td><input type="checkbox" id = A{{i}} value = A{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = B{{i}} value = B{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = C{{i}} value = C{{i}} name = "seat"/></td>
                        <td></td>
                        <td><input type="checkbox" id = D{{i}} value = D{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = E{{i}} value = E{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = F{{i}} value = F{{i}} name = "seat"/></td>
                        <td></td>
                        <td><input type="checkbox" id = G{{i}} value = G{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = H{{i}} value = H{{i}} name = "seat"/></td>
                        <td><input type="checkbox" id = I{{i}} value = I{{i}} name = "seat"/></td>
                    </tr>
                {% endfor %}
            </table> 
            </div>
            {% for seat in bookedseats %}
            <script>
                document.getElementById("{{seat}}").disabled = true;
            </script>
            {% endfor %}
            <p><input type = "submit" class="btn btn-success" value = "Submit"/></p>
            <h4 style="color:#E43F5A;">If no Seat/Food is submitted, any available Seat(s) will be choosen. </h4>
            <h4 style="color:#E43F5A;">You're booking will not be cancelled and you will still be charged.</h4>
            <h4 style="color:#E43F5A;">Please manually Cancel your Booking from Home Page or contact Staff.</h4>
        </div>
        </form>
    </body>
</html>

minesite/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Log in</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
    <div class="container">
    {% if errors %}
        {% for error in errors %}
        <div class="alert alert-danger">
            <strong>Alert! </strong>{{error}}
        </div>
        {% endfor %}
    {% endif %}
    </div>
        <body style="background-color: #162447;">
            <p></p>
            <div class = "container" style="padding: 2px; align-content: center; background-color: #E43F5A;">
                <div class="jumbotron" style="background-color: #E43F5A">
            <form name = "loginform" action = "{% url 'minesite:login' %}" method = "POST"> {% csrf_token %}
                <div class = "input-group">
                <h1 style="color:#162447;">Username: <input type = "text" style="background-color:lightgoldenrodyellow;" class="form-control" placeholder="Username" name = "username"/></h1>
                </div>
                <div class = "input-group">
                <h1 style="color:#162447;"> Password: <input type = "password" style="background-color:lightgoldenrodyellow;" class="form-control" placeholder="Password" name = "password"/></h1>
                </div>
                <p><input type = "submit" value = "Log in" class="btn btn-success"/>
                <input type = "button" value = "Create an Account here" onclick="window.location.href='http://127.0.0.1:8000/minesite/signup/'" class="btn btn-info"></p>     
        </form>
        </div>
    </div>
    </body> 
</html>

minesite/templates/seatconfirmed.html
<!DOCTYPE html>
<html>
    <head>
        <title>Booking Completed!</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
      <body style="background-color: #162447;">
        <div class = "container">
        <p></p>
        <h1 style="color:#E43F5A;">Booking Confirmed! Check Transactions for Ticket.</h1>
        <input type = "button" value = "Go Back to Home Page" class = "btn btn-info" onclick="window.location.href='http://127.0.0.1:8000/'">
        </div>
    </body>
</html>

minesite/templates/transactionpage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Review Transaction</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      </head>
        <body style="background-color: #162447;">
                <p></p>
            <div class="container">
                <p></p>
                <h1 style="color:#E43F5A;">Confirm Transaction</h1>
                </div>
                <p></p>
                <div class="progress">
                    <div class="progress-bar bg-success" style="width:50%">
                    </div>
                </div>
                <p></p>
                <div class = "container" style="padding: 2px; align-content: center; background-color: #E43F5A;">
        <form name = "transactionform" action="{% url 'minesite:transaction_page' %}" method = "post"> {% csrf_token %}
            <h4 style="color:#162447;">Booking Under: <input type="text" style="background-color:lightgoldenrodyellow" name = "username" value = {{username}} readonly/></h4>
            <h4 style="color:#162447;">From <input type="text" style="background-color:lightgoldenrodyellow" name = "fromplace" value = {{fromplace}} readonly/> To <input type="text" style="background-color:lightgoldenrodyellow" name = "toplace" value = {{toplace}} readonly/> - Flight <input type="text" name = "flightcode" style="background-color:lightgoldenrodyellow" value = {{flightcode}} readonly/></h4>
            <h4 style="color:#162447;"><input type="text" style="background-color:lightgoldenrodyellow" name = "flightclass" value = {{flightclass}} readonly/> Price - {{price}}</h4>
            <h4 style="color:#162447;">Number of Passangers - <input type="number" style="background-color:lightgoldenrodyellow" name = "num_passangers" value = {{number}} readonly/></h4>
            <h4 style="color:#162447;">Total(including Tax) - <input type="number" style="background-color:lightgoldenrodyellow" name = "total" value = {{total}} readonly/></h4>
            <h4><label for = "paymentmode">Choose the mode of Payment: </label>
            <select style="color:#162447;background-color:lightgoldenrodyellow" name = "paymentmode" id="paymentmode">
                <option value = "VISA">VISA</option>
                <option value = "PayPal">PayPal</option>
            </select></h4>
            <input type = "submit" class="btn btn-success" value = "Confirm Payment" />
            <input type = "button" class="btn btn-danger" value = "Go Back" onclick="history.back()">   
        </form>
        </div>    
    </body>
</html>